name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
      node-version: 18

    - name: Install AWS CLI and CDK
      run: |
        npm install -g aws-cdk
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade awscli

    - name: Authenticate AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy CDK
      run: cdk deploy

